#!/bin/sh

set -e

git config --get user.name > /dev/null
if [ $? -eq 1 ]; then
   git config --global user.name "Your Name"
fi

git config --get user.email > /dev/null
if [ $? -eq 1 ]; then
  git config --global user.email "you@example.com"
fi

bundle exec rake test

rm -Rf tmp

gem build change_agent.gemspec
